# Generated by Django 4.2.16 on 2024-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detailed_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="TrainingCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_name", models.CharField(max_length=40)),
                ("center_code", models.CharField(max_length=12, unique=True)),
                ("address", models.JSONField()),
                ("student_capacity", models.IntegerField(blank=True, null=True)),
                ("courses_offered", models.JSONField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_phone", models.CharField(max_length=15)),
            ],
        ),
    ]
